version: '3'
services:
  threads:
    build:
      context: ./services/threads
    environment:
      NODE_ENV: production
      PG_CONNECTION_STRING: postgres://postgres:postgrespassword@host.docker.internal:8432/postgres
      PORT: 4001
    ports: ['4001:4001']
  posts:
    build:
      context: ./services/posts
    environment:
      NODE_ENV: production
      PG_CONNECTION_STRING: postgres://postgres:postgrespassword@host.docker.internal:7432/postgres
      PORT: 4002
    ports: ['4002:4002']
  gateway:
    build:
      context: ./services/gateway
    depends_on:
      - threads
      - posts
    environment:
      NODE_ENV: production
      PORT: 8000
      THREADS_URL: http://host.docker.internal:4001
      POSTS_URL: http://host.docker.internal:4002
    ports: ['8000:8000']